name: EFADT Full Reproduce

on:
  schedule:
    # Runs at 00:00 every Sunday
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  reproduce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Reproduce Results
        run: make reproduce
